#BSUB -q normal
#BSUB -J changeTn5
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -R "span[ptile=2]"
#BSUB -n 2

# change names
mkdir split
split=split
mkdir $split/{1..192}

tmpdir=tmp
mv $tmpdir/filtered.TAG_TN_AACCATTGGA.bam $split/60/60.bam
mv $tmpdir/filtered.TAG_TN_AACCTGCGTA.bam $split/50/50.bam
mv $tmpdir/filtered.TAG_TN_AACCTGGTCT.bam $split/83/83.bam
mv $tmpdir/filtered.TAG_TN_AACTAGGCGC.bam $split/56/56.bam
mv $tmpdir/filtered.TAG_TN_AAGAAGCTAG.bam $split/39/39.bam
mv $tmpdir/filtered.TAG_TN_AAGACCGTTG.bam $split/87/87.bam
mv $tmpdir/filtered.TAG_TN_AAGCCAGTTA.bam $split/85/85.bam
mv $tmpdir/filtered.TAG_TN_AATACCATCC.bam $split/91/91.bam
mv $tmpdir/filtered.TAG_TN_AATCGATAAT.bam $split/64/64.bam
mv $tmpdir/filtered.TAG_TN_AATTAAGACT.bam $split/11/11.bam
mv $tmpdir/filtered.TAG_TN_ACCGCCAACC.bam $split/46/46.bam
mv $tmpdir/filtered.TAG_TN_ACCTGGCCAA.bam $split/95/95.bam
mv $tmpdir/filtered.TAG_TN_ACGAAGTCAA.bam $split/76/76.bam
mv $tmpdir/filtered.TAG_TN_ACGCGAGATT.bam $split/54/54.bam
mv $tmpdir/filtered.TAG_TN_ACGGAGGCGG.bam $split/9/9.bam
mv $tmpdir/filtered.TAG_TN_ACTATGCAAT.bam $split/25/25.bam
mv $tmpdir/filtered.TAG_TN_ACTCAATAGG.bam $split/16/16.bam
mv $tmpdir/filtered.TAG_TN_ACTTAACCTT.bam $split/34/34.bam
mv $tmpdir/filtered.TAG_TN_ACTTGCTAGA.bam $split/59/59.bam
mv $tmpdir/filtered.TAG_TN_AGAACGTCTC.bam $split/32/32.bam
mv $tmpdir/filtered.TAG_TN_AGAGAAGGTT.bam $split/41/41.bam
mv $tmpdir/filtered.TAG_TN_AGAGCCAAGG.bam $split/90/90.bam
mv $tmpdir/filtered.TAG_TN_AGAGCTATAA.bam $split/14/14.bam
mv $tmpdir/filtered.TAG_TN_AGCTCTCCTC.bam $split/92/92.bam
mv $tmpdir/filtered.TAG_TN_AGCTTATCCG.bam $split/93/93.bam
mv $tmpdir/filtered.TAG_TN_AGGTTAGCAT.bam $split/88/88.bam
mv $tmpdir/filtered.TAG_TN_AGGTTAGTTC.bam $split/71/71.bam
mv $tmpdir/filtered.TAG_TN_ATAAGGAGCA.bam $split/47/47.bam
mv $tmpdir/filtered.TAG_TN_ATCATATTAG.bam $split/23/23.bam
mv $tmpdir/filtered.TAG_TN_ATCCATGACT.bam $split/82/82.bam
mv $tmpdir/filtered.TAG_TN_ATCGGCTATC.bam $split/75/75.bam
mv $tmpdir/filtered.TAG_TN_CAACCGCTAA.bam $split/35/35.bam
mv $tmpdir/filtered.TAG_TN_CATACTCCGA.bam $split/42/42.bam
mv $tmpdir/filtered.TAG_TN_CATCTCTGCA.bam $split/94/94.bam
mv $tmpdir/filtered.TAG_TN_CATTCAATCA.bam $split/73/73.bam
mv $tmpdir/filtered.TAG_TN_CATTCGACGG.bam $split/72/72.bam
mv $tmpdir/filtered.TAG_TN_CCAGTTCCAA.bam $split/33/33.bam
mv $tmpdir/filtered.TAG_TN_CCATTATCTA.bam $split/65/65.bam
mv $tmpdir/filtered.TAG_TN_CCGAGAATCC.bam $split/5/5.bam
mv $tmpdir/filtered.TAG_TN_CCGATTCCTG.bam $split/45/45.bam
mv $tmpdir/filtered.TAG_TN_CGAACGCCGG.bam $split/48/48.bam
mv $tmpdir/filtered.TAG_TN_CGACGCGACT.bam $split/26/26.bam
mv $tmpdir/filtered.TAG_TN_CGCTCCTAAC.bam $split/81/81.bam
mv $tmpdir/filtered.TAG_TN_CGGATTAGAA.bam $split/74/74.bam
mv $tmpdir/filtered.TAG_TN_CGGTCAAGAA.bam $split/80/80.bam
mv $tmpdir/filtered.TAG_TN_CGTAGTTACC.bam $split/62/62.bam
mv $tmpdir/filtered.TAG_TN_CTAACTAGAT.bam $split/69/69.bam
mv $tmpdir/filtered.TAG_TN_CTAAGAGAAG.bam $split/15/15.bam
mv $tmpdir/filtered.TAG_TN_CTAGTAGTCT.bam $split/53/53.bam
mv $tmpdir/filtered.TAG_TN_CTGATGGTCA.bam $split/4/4.bam
mv $tmpdir/filtered.TAG_TN_CTTGCGCCGC.bam $split/17/17.bam
mv $tmpdir/filtered.TAG_TN_GAAGATCGAG.bam $split/38/38.bam
mv $tmpdir/filtered.TAG_TN_GACCTTGATA.bam $split/36/36.bam
mv $tmpdir/filtered.TAG_TN_GATACGGAAC.bam $split/27/27.bam
mv $tmpdir/filtered.TAG_TN_GATCGCTTCT.bam $split/68/68.bam
mv $tmpdir/filtered.TAG_TN_GATCTTACGC.bam $split/3/3.bam
mv $tmpdir/filtered.TAG_TN_GCAGGTCCGT.bam $split/30/30.bam
mv $tmpdir/filtered.TAG_TN_GCCATTCTCC.bam $split/20/20.bam
mv $tmpdir/filtered.TAG_TN_GCCGCAACGA.bam $split/6/6.bam
mv $tmpdir/filtered.TAG_TN_GCGTTGGAGC.bam $split/2/2.bam
mv $tmpdir/filtered.TAG_TN_GCTAACTTGC.bam $split/43/43.bam
mv $tmpdir/filtered.TAG_TN_GCTGGAACTT.bam $split/70/70.bam
mv $tmpdir/filtered.TAG_TN_GGAGGATAGC.bam $split/78/78.bam
mv $tmpdir/filtered.TAG_TN_GGCAGACGCC.bam $split/51/51.bam
mv $tmpdir/filtered.TAG_TN_GGCTCTCTAT.bam $split/79/79.bam
mv $tmpdir/filtered.TAG_TN_GGCTGAGCTC.bam $split/44/44.bam
mv $tmpdir/filtered.TAG_TN_GGTACCGGCA.bam $split/84/84.bam
mv $tmpdir/filtered.TAG_TN_GGTACTGCCT.bam $split/18/18.bam
mv $tmpdir/filtered.TAG_TN_GGTATCCGCC.bam $split/55/55.bam
mv $tmpdir/filtered.TAG_TN_GGTATGCTTG.bam $split/49/49.bam
mv $tmpdir/filtered.TAG_TN_TAACTGGTTA.bam $split/96/96.bam
mv $tmpdir/filtered.TAG_TN_TAGAATTAAC.bam $split/19/19.bam
mv $tmpdir/filtered.TAG_TN_TAGAGTAATA.bam $split/29/29.bam
mv $tmpdir/filtered.TAG_TN_TAGATCTACT.bam $split/10/10.bam
mv $tmpdir/filtered.TAG_TN_TAGCCGTCAT.bam $split/52/52.bam
mv $tmpdir/filtered.TAG_TN_TATATACTAA.bam $split/58/58.bam
mv $tmpdir/filtered.TAG_TN_TCAACGTAAG.bam $split/66/66.bam
mv $tmpdir/filtered.TAG_TN_TCCAATCATC.bam $split/63/63.bam
mv $tmpdir/filtered.TAG_TN_TCCGGCCTCG.bam $split/40/40.bam
mv $tmpdir/filtered.TAG_TN_TCCTACCAGT.bam $split/1/1.bam
mv $tmpdir/filtered.TAG_TN_TCGCGGTTGG.bam $split/61/61.bam
mv $tmpdir/filtered.TAG_TN_TCGCTAAGCA.bam $split/57/57.bam
mv $tmpdir/filtered.TAG_TN_TCGGCCTTAC.bam $split/31/31.bam
mv $tmpdir/filtered.TAG_TN_TCTAATAGTA.bam $split/67/67.bam
mv $tmpdir/filtered.TAG_TN_TCTGATACCA.bam $split/37/37.bam
mv $tmpdir/filtered.TAG_TN_TCTTGCCGAC.bam $split/86/86.bam
mv $tmpdir/filtered.TAG_TN_TGAGTCTGGC.bam $split/7/7.bam
mv $tmpdir/filtered.TAG_TN_TGCCGGCAGA.bam $split/21/21.bam
mv $tmpdir/filtered.TAG_TN_TGCGGACCTA.bam $split/8/8.bam
mv $tmpdir/filtered.TAG_TN_TGGTCAGCCA.bam $split/24/24.bam
mv $tmpdir/filtered.TAG_TN_TTACCGAGGC.bam $split/22/22.bam
mv $tmpdir/filtered.TAG_TN_TTACCTCGAC.bam $split/77/77.bam
mv $tmpdir/filtered.TAG_TN_TTATCCGGAT.bam $split/28/28.bam
mv $tmpdir/filtered.TAG_TN_TTATTCATTC.bam $split/12/12.bam
mv $tmpdir/filtered.TAG_TN_TTCGCCTCCA.bam $split/89/89.bam
mv $tmpdir/filtered.TAG_TN_TTGACTTCAG.bam $split/13/13.bam

mv $tmpdir/filtered.TAG_TN_TTCTCGCATG.bam $split/97/97.bam
mv $tmpdir/filtered.TAG_TN_ACCTCGTTGA.bam $split/98/98.bam
mv $tmpdir/filtered.TAG_TN_CCATTGCGTT.bam $split/99/99.bam
mv $tmpdir/filtered.TAG_TN_ATCTCCGAAC.bam $split/100/100.bam
mv $tmpdir/filtered.TAG_TN_GGCAGGTATT.bam $split/101/101.bam
mv $tmpdir/filtered.TAG_TN_AATCGTAGCG.bam $split/102/102.bam
mv $tmpdir/filtered.TAG_TN_GGCGTTAAGG.bam $split/103/103.bam
mv $tmpdir/filtered.TAG_TN_AGGAGCGGTA.bam $split/104/104.bam
mv $tmpdir/filtered.TAG_TN_AATCCATCTT.bam $split/105/105.bam
mv $tmpdir/filtered.TAG_TN_TGGCCTGAAG.bam $split/106/106.bam
mv $tmpdir/filtered.TAG_TN_AACCTCATTC.bam $split/107/107.bam
mv $tmpdir/filtered.TAG_TN_CCTGGAAGAG.bam $split/108/108.bam
mv $tmpdir/filtered.TAG_TN_GGAGGTTCTA.bam $split/109/109.bam
mv $tmpdir/filtered.TAG_TN_ATCATCAACG.bam $split/110/110.bam
mv $tmpdir/filtered.TAG_TN_GAAGAGGCAT.bam $split/111/111.bam
mv $tmpdir/filtered.TAG_TN_AACCGCTGGT.bam $split/112/112.bam
mv $tmpdir/filtered.TAG_TN_CCTTGATCGT.bam $split/113/113.bam
mv $tmpdir/filtered.TAG_TN_ACCGAAGACC.bam $split/114/114.bam
mv $tmpdir/filtered.TAG_TN_CTTGATTGCC.bam $split/115/115.bam
mv $tmpdir/filtered.TAG_TN_AAGAATCTGA.bam $split/116/116.bam
mv $tmpdir/filtered.TAG_TN_TTGCTAACGG.bam $split/117/117.bam
mv $tmpdir/filtered.TAG_TN_ACTAGAGAGT.bam $split/118/118.bam
mv $tmpdir/filtered.TAG_TN_AATGCCGCTT.bam $split/119/119.bam
mv $tmpdir/filtered.TAG_TN_TATAGACGCA.bam $split/120/120.bam
mv $tmpdir/filtered.TAG_TN_TCAATCGCAT.bam $split/121/121.bam
mv $tmpdir/filtered.TAG_TN_TTCTTAATAA.bam $split/122/122.bam
mv $tmpdir/filtered.TAG_TN_GTCCTAGAGG.bam $split/123/123.bam
mv $tmpdir/filtered.TAG_TN_ATATTGATAC.bam $split/124/124.bam
mv $tmpdir/filtered.TAG_TN_CCGCTGCCAG.bam $split/125/125.bam
mv $tmpdir/filtered.TAG_TN_CCTAGTACGT.bam $split/126/126.bam
mv $tmpdir/filtered.TAG_TN_CAATTACCGT.bam $split/127/127.bam
mv $tmpdir/filtered.TAG_TN_GGCCGTAGTC.bam $split/128/128.bam
mv $tmpdir/filtered.TAG_TN_CGATTACGGC.bam $split/129/129.bam
mv $tmpdir/filtered.TAG_TN_TAATGAACGA.bam $split/130/130.bam
mv $tmpdir/filtered.TAG_TN_CCGTTCCTTA.bam $split/131/131.bam
mv $tmpdir/filtered.TAG_TN_GGTACCATAT.bam $split/132/132.bam
mv $tmpdir/filtered.TAG_TN_CCGATTCGCA.bam $split/133/133.bam
mv $tmpdir/filtered.TAG_TN_ATGGCTCTGC.bam $split/134/134.bam
mv $tmpdir/filtered.TAG_TN_GTATAATACG.bam $split/135/135.bam
mv $tmpdir/filtered.TAG_TN_ATCAGCAAGT.bam $split/136/136.bam
mv $tmpdir/filtered.TAG_TN_GGCGAACTCG.bam $split/137/137.bam
mv $tmpdir/filtered.TAG_TN_TTAATTGAAT.bam $split/138/138.bam
mv $tmpdir/filtered.TAG_TN_TTAGGACCGG.bam $split/139/139.bam
mv $tmpdir/filtered.TAG_TN_AAGTAAGAGC.bam $split/140/140.bam
mv $tmpdir/filtered.TAG_TN_CCTTGGTCCA.bam $split/141/141.bam
mv $tmpdir/filtered.TAG_TN_CATCAGAATG.bam $split/142/142.bam
mv $tmpdir/filtered.TAG_TN_TTATAGCAGA.bam $split/143/143.bam
mv $tmpdir/filtered.TAG_TN_TTACTTGGAA.bam $split/144/144.bam
mv $tmpdir/filtered.TAG_TN_GCTCAGCCGG.bam $split/145/145.bam
mv $tmpdir/filtered.TAG_TN_ACGTCCGCAG.bam $split/146/146.bam
mv $tmpdir/filtered.TAG_TN_TTGACTGACG.bam $split/147/147.bam
mv $tmpdir/filtered.TAG_TN_TTGCGAGGCA.bam $split/148/148.bam
mv $tmpdir/filtered.TAG_TN_TTCCAACCGC.bam $split/149/149.bam
mv $tmpdir/filtered.TAG_TN_TAACCTTCGG.bam $split/150/150.bam
mv $tmpdir/filtered.TAG_TN_TCAAGCCGAT.bam $split/151/151.bam
mv $tmpdir/filtered.TAG_TN_CTTGCAACCT.bam $split/152/152.bam
mv $tmpdir/filtered.TAG_TN_CCATCGCGAA.bam $split/153/153.bam
mv $tmpdir/filtered.TAG_TN_TAGACTTCTT.bam $split/154/154.bam
mv $tmpdir/filtered.TAG_TN_GTCCTTAAGA.bam $split/155/155.bam
mv $tmpdir/filtered.TAG_TN_AGTAACGGTC.bam $split/156/156.bam
mv $tmpdir/filtered.TAG_TN_GTTCGTCAGA.bam $split/157/157.bam
mv $tmpdir/filtered.TAG_TN_CGCCTAATGC.bam $split/158/158.bam
mv $tmpdir/filtered.TAG_TN_ACCGGAATTA.bam $split/159/159.bam
mv $tmpdir/filtered.TAG_TN_TAGGCCATAG.bam $split/160/160.bam
mv $tmpdir/filtered.TAG_TN_TAACTCTTAG.bam $split/161/161.bam
mv $tmpdir/filtered.TAG_TN_TATGAGTTAA.bam $split/162/162.bam
mv $tmpdir/filtered.TAG_TN_TATCATGATC.bam $split/163/163.bam
mv $tmpdir/filtered.TAG_TN_GAGCATATGG.bam $split/164/164.bam
mv $tmpdir/filtered.TAG_TN_TAACGATCCA.bam $split/165/165.bam
mv $tmpdir/filtered.TAG_TN_CGGCGTAACT.bam $split/166/166.bam
mv $tmpdir/filtered.TAG_TN_CGTCGCAGCC.bam $split/167/167.bam
mv $tmpdir/filtered.TAG_TN_GTAGCTCCAT.bam $split/168/168.bam
mv $tmpdir/filtered.TAG_TN_TTGCCTTGGC.bam $split/169/169.bam
mv $tmpdir/filtered.TAG_TN_TGCTAATTCT.bam $split/170/170.bam
mv $tmpdir/filtered.TAG_TN_GTCCTACTTG.bam $split/171/171.bam
mv $tmpdir/filtered.TAG_TN_GGTAGGTTAG.bam $split/172/172.bam
mv $tmpdir/filtered.TAG_TN_GAGCATCATT.bam $split/173/173.bam
mv $tmpdir/filtered.TAG_TN_CCGCTCCGGC.bam $split/174/174.bam
mv $tmpdir/filtered.TAG_TN_TTCTTCCGGT.bam $split/175/175.bam
mv $tmpdir/filtered.TAG_TN_AGGAGAGAAC.bam $split/176/176.bam
mv $tmpdir/filtered.TAG_TN_TAACTCAATT.bam $split/177/177.bam
mv $tmpdir/filtered.TAG_TN_ACTATAGGTT.bam $split/178/178.bam
mv $tmpdir/filtered.TAG_TN_CAAGATGCCG.bam $split/179/179.bam
mv $tmpdir/filtered.TAG_TN_AACGTCTAGT.bam $split/180/180.bam
mv $tmpdir/filtered.TAG_TN_AGGTATACTC.bam $split/181/181.bam
mv $tmpdir/filtered.TAG_TN_TTCATAGGAC.bam $split/182/182.bam
mv $tmpdir/filtered.TAG_TN_GGAGGCCTCC.bam $split/183/183.bam
mv $tmpdir/filtered.TAG_TN_TTCAATATAA.bam $split/184/184.bam
mv $tmpdir/filtered.TAG_TN_ACGTCATATA.bam $split/185/185.bam
mv $tmpdir/filtered.TAG_TN_TTGACCAGGA.bam $split/186/186.bam
mv $tmpdir/filtered.TAG_TN_CGGTTGCGCG.bam $split/187/187.bam
mv $tmpdir/filtered.TAG_TN_CAAGGAGGTC.bam $split/188/188.bam
mv $tmpdir/filtered.TAG_TN_TTACGATGAA.bam $split/189/189.bam
mv $tmpdir/filtered.TAG_TN_TTGCTGGCAT.bam $split/190/190.bam
mv $tmpdir/filtered.TAG_TN_GAGGCATCAA.bam $split/191/191.bam
mv $tmpdir/filtered.TAG_TN_ATTCGACCAA.bam $split/192/192.bam


